import Foundation
import os

#if canImport(UIKit)
import UIKit
#endif

/// Keeps the Home Screen icon looking like the pet that lives in the app: adopt a charcoal
/// dragon and the icon becomes a charcoal dragon.
///
/// iOS can only show an icon that was compiled into the bundle, so there is one icon set per
/// species and coat swatch — `AppIcon-<species>-<coat>`, generated by
/// `Tools/GenerateAppIcons.swift` and shipped via the target's Include All App Icon Assets
/// build setting. A coat that came from the colour picker rather than a swatch lands on
/// whichever swatch is nearest. Belly, accent and size aren't reflected; none of them read
/// at icon size. The primary `AppIcon` — a paw print, no species implied — is what shows
/// before anyone has adopted anything.
enum PetAppIcon {
    private nonisolated static let logger = Logger(subsystem: "PetPhone", category: "AppIcon")

    /// The asset catalog name for how this pet looks right now.
    nonisolated static func name(for pet: Pet) -> String {
        // A pet that has never been recoloured gets the species' own icon, whose stock
        // coat isn't necessarily one of the swatches.
        guard let coat = pet.appearance.coat else {
            return "AppIcon-\(pet.kind.rawValue)-stock"
        }
        guard let swatch = PetSwatches.coat.min(by: {
            distance($0.color, coat) < distance($1.color, coat)
        }) else {
            return "AppIcon"
        }
        return "AppIcon-\(pet.kind.rawValue)-\(swatch.slug)"
    }

    /// Plain squared distance in sRGB. The ready-made coats are far apart enough that
    /// nothing cleverer earns its keep.
    private nonisolated static func distance(_ one: PetColor, _ other: PetColor) -> Double {
        let red = one.red - other.red
        let green = one.green - other.green
        let blue = one.blue - other.blue
        return red * red + green * green + blue * blue
    }

    /// False where the system won't let an app change its icon — the Mac and visionOS
    /// builds have no alternate icons at all.
    static var isSupported: Bool {
        #if canImport(UIKit)
        UIApplication.shared.supportsAlternateIcons
        #else
        false
        #endif
    }

    /// The icon set on the Home Screen right now, or `nil` for the paw print.
    static var currentName: String? {
        #if canImport(UIKit)
        UIApplication.shared.alternateIconName
        #else
        nil
        #endif
    }

    /// Points the Home Screen icon at `pet`, or back at the paw print when there is no pet.
    /// Fire and forget; use ``set(_:)`` to wait for the result.
    ///
    /// Deliberately not called when the owner recolours a pet: the system puts an alert on
    /// screen for every icon change, and a colour picker drag would fire hundreds. The
    /// button in Settings is how a redesigned pet gets onto the Home Screen.
    static func apply(for pet: Pet?) {
        Task { await set(pet) }
    }

    /// Switches the icon and waits for the system to finish, reporting whether the icon
    /// now shows `pet`.
    @discardableResult
    static func set(_ pet: Pet?) async -> Bool {
        #if canImport(UIKit)
        let application = UIApplication.shared
        guard application.supportsAlternateIcons else { return false }

        // Passing nil restores the primary icon. Setting the icon that is already showing
        // would pop the system's "you have changed the icon" alert for no reason.
        let wanted = pet.map(name(for:))
        guard wanted != application.alternateIconName else { return true }

        // The completion handler arrives on a UIKit queue, and the error itself isn't
        // Sendable, so only its description comes back across.
        let failure: String? = await withCheckedContinuation { continuation in
            application.setAlternateIconName(wanted) { error in
                continuation.resume(returning: error?.localizedDescription)
            }
        }
        if let failure {
            logger.error("Could not switch the app icon to \(wanted ?? "AppIcon", privacy: .public): \(failure, privacy: .public)")
            return false
        }
        return true
        #else
        false
        #endif
    }
}
